version: "3.9"
services:
  vaultwarden:
    image: vaultwarden/server:1.28.1-alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./bitwarden-data/:/data/
    environment:
      - DOMAIN=https://localhost
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - ADMIN_TOKEN=YourReallyStrongAdminTokenHere
      - SENDS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
      - SIGNUPS_ALLOWED=true
      - SIGNUPS_VERIFY=false
